import os
import sipconfig
from PyQt5 import QtCore

# You should modify to get exact directory paths to SIP, Qt
home_dir = os.path.expanduser('~')
sip_inc_dir = "/home/zhiping/Projects/boost_practice/PyQt5_gpl-5.11.3/sip"
qt_inc_dir = home_dir + "/Applications/Qt/5.10.1/gcc_64/include"

target_dir = os.getcwd()

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "notificationcenter.sbf"

# Get the PyQt configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.  Note that we tell SIP where to find the qt
# module's specification files using the -I flag.
print(QtCore.PYQT_CONFIGURATION["sip_flags"])
os.system(" ".join([config.sip_bin, "-c", ".", "-b", build_file,
                    "-I" + sip_inc_dir,
                    "-I/home/zhiping/Projects/boost_practice/hello-sip-pyqt5/sip_build/include",
                    QtCore.PYQT_CONFIGURATION["sip_flags"],
                    "notificationcenter.sip"]))

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)
# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
extraFlags = "-std=c++11 -I%s -I%s/QtCore -I%s/QtGui -I%s -I%s/QtWidgets -I/home/zhiping/Projects/boost_practice/PyQt5_gpl-5.11.3/qpy/QtWidgets -I/home/zhiping/Projects/LinuxNotifier/NotificationCenter/NotificationCenter -I/home/zhiping/Projects/boost_practice/PyQt5_gpl-5.11.3/qpy/QtGui" % (qt_inc_dir, qt_inc_dir, qt_inc_dir, "/home/zhiping/Projects/boost_practice/hello-sip-pyqt5/sip_build/include", qt_inc_dir)
makefile.extra_cflags = [extraFlags]
makefile.extra_cxxflags = [extraFlags]
makefile.extra_lflags = ["-Wl,-R" + target_dir]
makefile.extra_lib_dirs = [target_dir]
makefile.extra_libs = ["NCCore"]

# Generate the Makefile itself.
makefile.generate()
