import os
import sys
import sipconfig
from PyQt5 import QtCore

# You should modify to get exact directory paths to SIP, Qt
home_dir = os.path.expanduser('~')

if len(sys.argv) < 4:
    print("python3 configure.py <project-dir> <qt_dir> <sip_dir> <pyqt_sip_dir>")
    sys.exit(1)
project_dir = sys.argv[1]
qt_dir = sys.argv[2]
sip_dir = sys.argv[3]
pyqt_sip_dir = sys.argv[4]

qt_inc_dir = qt_dir + '/include'

target_dir = os.getcwd()

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "notificationcenter.sbf"

# Get the PyQt configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.  Note that we tell SIP where to find the qt
# module's specification files using the -I flag.
print(QtCore.PYQT_CONFIGURATION["sip_flags"])
os.system(" ".join([config.sip_bin, "-c", ".", "-b", build_file,
                    "-I" + pyqt_sip_dir,
                    "-I" + sip_dir + "/include",
                    QtCore.PYQT_CONFIGURATION["sip_flags"],
                    "notificationcenter.sip"]))

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)
# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
extraFlags = "-std=c++11 -I%s -I%s/QtCore -I%s/QtGui -I%s -I%s/QtWidgets -I%s/qpy/QtWidgets -I%s/NotificationCenter -Ii%s/qpy/QtGui" % (qt_inc_dir, qt_inc_dir, qt_inc_dir, sip_dir + '/include', qt_inc_dir, pyqt_sip_dir, project_dir, pyqt_sip_dir)
makefile.extra_cflags = [extraFlags]
makefile.extra_cxxflags = [extraFlags]
makefile.extra_lflags = ["-Wl,-R" + target_dir]
makefile.extra_lib_dirs = [target_dir]
makefile.extra_libs = ["NCCore"]

# Generate the Makefile itself.
makefile.generate()
